spring.application.name=kafka-stream

# Server
server.port=8083

# Kafka
spring.kafka.bootstrap-servers=127.0.0.1:9092

# Kafka Streams
spring.kafka.streams.application-id=order-stream-app
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde
spring.kafka.streams.properties.spring.json.trusted.packages=*
#spring.kafka.streams.properties.spring.json.value.default.type=com.bksoft.kafka_stream.model.Order

# Custom Application Properties
app.kafka.order-topic=orders
app.kafka.high-value-order-topic=high-value-orders

app.kafka.sensor-topic=sensors
app.kafka.high-temperatures-topic=high-temperatures-sensors
app.kafka.high-temperatures-5min-topic=high-temperatures-5min